config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :posts do
    

    collection do
      get :feeds
      get :sort
    end

    member do
      post :favorite
      post :unfavorite
    end
  end
  
  resources :replies, only: [:create, :edit, :update, :destroy]
  resources :friendships, only: [:create, :destroy] do
    post :confirm
    delete :reject
  end


  resources :users, only: [:show, :edit, :update] do
    member do
      get :comment
      get :collect
      get :draft
      get :friend
    end
  end
  
  resources :categories, only: :show
  root "posts#index"

  namespace :admin do
    resources :categories
    root "categories#index"

    resources :users, only: [:index, :update]
  end

  namespace :api, defaults: {format: :json} do
    namespace :v1 do
      post "/login" => "auth#login"
      post "/logout" => "auth#logout"
      
      resources :posts, only: [:index, :show, :create, :update, :destroy]
    end
  end
end

app/models/post.rb
class Post < ApplicationRecord
  mount_uploader :image, PhotoUploader

  validates_presence_of :title, :description, :categories, :authority, :message => "標題、內容、分類、文章權限必填"
  
  belongs_to :user

  has_many :post_categories, dependent: :destroy
  has_many :categories, through: :post_categories

  has_many :replies, dependent: :destroy

  has_many :favorites, dependent: :destroy
  has_many :favorited_users, through: :favorites, source: :user

  def is_favorited?(user)
    self.favorited_users.include?(user)
  end

  def is_published?
    self.status == true
  end

  def self.check_authority(user)
    self.where("authority = ? OR user_id = ?", "All", user.id).or(where('authority = ? AND user_id IN (?)', "Friends", user.all_friends))
  end
    
end

app/views/shared/_admin_tabs.html.erb
<ul class="admin-tab clearfix">
  <li role="presentation" class="<%= 'active' if selected_item == 'Category List' %>"><%= link_to "Category List", admin_categories_path %></li>
  <li role="presentation" class="<%= 'active' if selected_item == 'User List' %>"><%= link_to "User List", admin_users_path %></li>
</ul>

app/views/shared/_form.html.erb
  <%= form_for  @post do |f| %>
    <%= f.label :title, "Title" %>
    <%= f.text_field :title, class:"form-control" %> <br>

    <%= f.label :description, "Description" %>
    <%= f.text_area :description, class:"form-control" %> <br>

    <%= f.label :image, "Photo" %>
    <%= image_tag @post.image, width: '300px' if @post.image? %>
    <%= f.file_field :image %> <br>

    <%= f.label :authority, "Who can see：" %>
    <%= f.radio_button :authority ,"All",:checked => true %>
    <%= f.label :authority, "All" %> &nbsp; 
    <%= f.radio_button :authority ,"Friends" %>
    <%= f.label :authority, "Friends" %> &nbsp; 
    <%= f.radio_button :authority ,"Myself" %>
    <%= f.label :authority, "Myself" %> <br>

    <%= f.label :category_ids, "Category：" %>
    <%= f.collection_check_boxes(:category_ids, Category.all, :id, :name) do |category| %>    
      <%= category.check_box %> <%= category.label %> &nbsp; 
    <% end %> <br>
    
    <% if @post.status != true || @post.title == nil || @post.description == nil || @post.category_ids == [] %>
      <%= f.submit "Save Draft", :class => 'btn btn-default' %>
      <%= f.submit  'Submit', :class => 'btn btn-primary' %>
    <% else %>
      <%= f.submit  'Update', :class => 'btn btn-primary' %>
    <% end %>
  <% end %>

app/views/shared/_friend.html.erb
<% if user != current_user %>
  <% if current_user.friend?(user)%>
    <%= link_to '取消好友', friendship_path(user), method: :delete, class: "btn btn-default btn-sm" %>
  <% elsif current_user.pending_friend?(user) %>
    <%= link_to "取消好友邀請", friendship_path(user), method: :delete, class: "btn btn-danger btn-sm" %>
  <% elsif current_user.requested_friend?(user) %>
    <%= link_to "接受好友邀請", friendship_confirm_path(user), method: :post, class: "btn btn-info btn-sm" %>
    <%= link_to "拒絕好友邀請", friendship_reject_path(user), method: :delete, class: "btn btn-danger btn-sm" %>
  <% else %>
    <%= link_to '加入好友', friendships_path(friend_id: user), method: :post, class: "btn btn-warning btn-sm"%>
  <% end %>
<% end %>

app/views/shared/_header.html.erb
<link href="https://fonts.googleapis.com/css?family=Sigmar+One" rel="stylesheet">
<nav class="navbar navbar-inverse" style="margin-bottom: 0px;">
  <div class="container-fluid">
     <div class="navbar-header">
       <%= link_to  root_path, class: "navbar-brand" do %>
        <p style="font-family: 'Sigmar One', cursive; font-size: 20px;">Dojo</p> 
       <% end %>
     </div>
     <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
          <li><%= link_to ' Feeds <i class="glyphicon glyphicon-fire" aria-hidden="true"></i>'.html_safe, feeds_posts_path %></li>
          <li><%= link_to ' All Post <i class="glyphicon glyphicon-list" aria-hidden="true"></i>'.html_safe, posts_path %></li>
          <li><%= link_to ' New Post <i class="glyphicon glyphicon-file" aria-hidden="true"></i>'.html_safe, new_post_path %></li>
      </ul>
       <ul class="pull-right text-right nav navbar-nav">
          <% if current_user %>
            <% if current_user.admin? %>
              <li><%= link_to '<i class="glyphicon glyphicon-inbox" aria-hidden="true"></i> '.html_safe, admin_categories_path %></li>
            <% end %>
          <li><p class="navbar-text">Hi, <%= current_user.name if current_user.name? %>
          <%= current_user.email.split("@").first unless current_user.name? %></p></li>
          <li><%= link_to '<i class="glyphicon glyphicon-user" aria-hidden="true"></i> '.html_safe, user_path(current_user) %></li>
          <li><%= link_to('<i class="glyphicon glyphicon-log-out" aria-hidden="true"></i> '.html_safe, destroy_user_session_path, method: :delete) %></li>
          <li><%= link_to('<i class="glyphicon glyphicon-wrench" aria-hidden="true"></i> '.html_safe, edit_user_registration_path) %></li>
          <% else %>
          <li><%= link_to('註冊', new_user_registration_path) %></li>
          <li><%= link_to('<i class="glyphicon glyphicon-log-in" aria-hidden="true"></i> '.html_safe, new_user_session_path) %></li>
         <% end %>
       </ul>
     </div>
  </div>
</nav>

app/views/shared/_post_list.html.erb
<table class="table table-hover">
  <thead>
    <tr>
      <th style="text-align: center;">
        <%= link_to sort_posts_path(category_id: @category, replies_count: true)  do %>
          Replies count <i class="glyphicon glyphicon-chevron-down" aria-hidden="true"></i>
        <% end %>
      </th>
      <th style="text-align: center;">Title</th>
      <th style="text-align: center;">
        <%= link_to sort_posts_path(category_id: @category, last_replied_at: true)  do %>
          Last replied at <i class="glyphicon glyphicon-chevron-down" aria-hidden="true"></i>
        <% end %>
      </th>
      <th style="text-align: center;">
        <%= link_to sort_posts_path(category_id: @category, viewed_count: true)  do %>
          Viewed count <i class="glyphicon glyphicon-chevron-down" aria-hidden="true"></i>
        <% end %>
      </th>
    </tr>
  </thead>
  <tbody style="text-align: center;">
    <% @posts.each do |post| %>
    <tr>
      <td><span  class="label label-warning"><%= post.replies_count %></span></td>
      <td style="text-align: left;">
        <%= link_to post_path(post) do %>
          <%= post.title %>
        <% end %>
      </td>
      <td>
        <% if post.replies_count != 0 %>
          <%= post.replies.last.created_at.to_s[0..9] %>
        <% else %>
          No reply
        <% end %>
      </td>
      <td><i class="glyphicon glyphicon-eye-open" aria-hidden="true"></i> &nbsp;<%= post.viewed_count %></td>
    </tr>
    <% end %>
  </tbody>
</table>

<div class="text-center">
  <%= paginate @posts %>
</div>

app/views/shared/_user_info.html.erb
<div class="page-header">
  <div class="col-md-3 col-sm-4">
    <div class="text-center">
      <%= image_tag @user.avatar, class: "img-responsive img-rounded" if @user.avatar?%>
      <%= image_tag "http://via.placeholder.com/400x400", class: "img-responsive img-rounded"  unless @user.avatar?%> 
      <h3><%= @user.name if @user.name? %>
      <%= @user.email.split("@").first.upcase_first unless @user.name? %>
      </h3>
      <%= render partial: "shared/friend", locals: {user: @user} %>
    </div>
  </div>
  <div class="col-md-9 col-sm-8">
    <p><strong><%= @user.email %></strong></p>
    <div><%= simple_format @user.introduction %></div>
    <% if @user.email == current_user.email %>
      <%= link_to '編輯個人資料', edit_user_path(@user), class: "btn btn-primary" %>
    <% end %>
  </div>
  <div class="clearfix"></div>
</div>

app/views/shared/_user_tabs.html.erb
<ul class="user-tab clearfix">
  <li role="presentation" class="<%= 'active' if selected_item == '我的文章' %>"><%= link_to "我的文章", user_path(@user) %></li>
  <li role="presentation" class="<%= 'active' if selected_item == '我的留言' %>"><%= link_to "我的留言", comment_user_path(@user) %></li>
  <% if @user == current_user %>
    <li role="presentation" class="<%= 'active' if selected_item == '我的收藏' %>"><%= link_to "我的收藏", collect_user_path(@user) %></li>
    <li role="presentation" class="<%= 'active' if selected_item == '我的草稿' %>"><%= link_to "我的草稿", draft_user_path(@user) %></li>
    <li role="presentation" class="<%= 'active' if selected_item == '我的好友' %>"><%= link_to "我的好友", friend_user_path(@user) %></li>
  <% end %>
</ul>