config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :posts do
    

    collection do
      get :feeds
      get :sort
    end

    member do
      post :favorite
      post :unfavorite
    end
  end
  
  resources :replies, only: [:create, :edit, :update, :destroy]
  resources :friendships, only: [:create, :destroy] do
    post :confirm
    delete :reject
  end


  resources :users, only: [:show, :edit, :update] do
    member do
      get :comment
      get :collect
      get :draft
      get :friend
    end
  end
  
  resources :categories, only: :show
  root "posts#index"

  namespace :admin do
    resources :categories
    root "categories#index"

    resources :users, only: [:index, :update]
  end

  namespace :api, defaults: {format: :json} do
    namespace :v1 do
      post "/login" => "auth#login"
      post "/logout" => "auth#logout"
      
      resources :posts, only: [:index, :show, :create, :update, :destroy]
    end
  end
end

app/models/category.rb
class Category < ApplicationRecord
  validates_presence_of :name
  
  has_many :post_categories, dependent: :restrict_with_error
  has_many :posts, through: :post_categories
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < ApplicationController
  
  before_action :authenticate_admin

  before_action :set_category, only: [:update, :destroy]

  def index
    @categories = Category.all

    if params[:id]
      set_category
    else
      @category = Category.new
    end
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:notice] = "分類創建成功"
      redirect_to admin_categories_path

    else
      @categories = Category.all
      render :index
    end
  end

  def update
    
    if @category.update(category_params)
      redirect_to admin_categories_path
      flash[:notice] = "分類更新成功"
    else
      @categories = Category.all
      render :index
    end
  end

  def destroy
    if @category.destroy
      @category.destroy
      flash[:alert] = "分類刪除成功"
      redirect_to admin_categories_path
    else
      flash[:alert] = "分類刪除失敗"
      redirect_to admin_categories_path
    end
  end

  private

  def category_params
    params.require(:category).permit(:name)
  end

  def set_category
    @category = Category.find(params[:id])
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  layout "site_index", only: [:show]

  def show
    @categories = Category.all
    @category = Category.find(params[:id])
    @posts = @category.posts.where('status = ?', true).order(created_at: :asc).page(params[:page]).per(20)
    if user_signed_in?
      @posts = @posts.check_authority(current_user)
    end
  end
end

app/helpers/admin/categories_helper.rb
module Admin::CategoriesHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/admin/categories/index.html.erb
<div class="container">
  <%= render :partial => "shared/admin_tabs", :locals => { :selected_item => 'Category List' } %>
  <div class="row">
    <div class="col-md-12">
      <div class="form-inline" >
        <%= form_for [:admin, @category] do |f| %>
          <div class="form-group">
            <%= f.text_field :name, placeholder: "請輸入欲新增分類", class: "form-control" %>
          </div>
          <%= f.submit "Submit", class: "btn btn-primary" %> 
          <% if @category.errors.any? %>
            <%= @category.errors.full_messages.to_sentence %>
          <% end %>     
        <% end %>
      </div> 
      <br> 
      <table class="table table-striped table-bordered">
        <thead>
          <tr>
            <th>Category Name</th>
            <th>功能</th>
          </tr>
        </thead>
        <tbody>
          <% @categories.each do |category| %>
          <tr>
            <td><%= category.name %></td>
            <td>
              <%= link_to '<i class="glyphicon glyphicon-pencil" aria-hidden="true"> 編輯</i>'.html_safe, admin_categories_path(id: category.id), class: "btn btn-default btn-sm" %> ｜
              <%= link_to '<i class="glyphicon glyphicon-trash" aria-hidden="true"> 刪除</i>'.html_safe, admin_category_path(category), method: :delete, data: { confirm: "Are you sure?"}, class: "btn btn-default btn-sm" %>
            </td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>