config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :posts do
    

    collection do
      get :feeds
      get :sort
    end

    member do
      post :favorite
      post :unfavorite
    end
  end
  
  resources :replies, only: [:create, :edit, :update, :destroy]
  resources :friendships, only: [:create, :destroy] do
    post :confirm
    delete :reject
  end


  resources :users, only: [:show, :edit, :update] do
    member do
      get :comment
      get :collect
      get :draft
      get :friend
    end
  end
  
  resources :categories, only: :show
  root "posts#index"

  namespace :admin do
    resources :categories
    root "categories#index"

    resources :users, only: [:index, :update]
  end

  namespace :api, defaults: {format: :json} do
    namespace :v1 do
      post "/login" => "auth#login"
      post "/logout" => "auth#logout"
      
      resources :posts, only: [:index, :show, :create, :update, :destroy]
    end
  end
end

app/models/post.rb
class Post < ApplicationRecord
  mount_uploader :image, PhotoUploader

  validates_presence_of :title, :description, :categories, :authority, :message => "標題、內容、分類、文章權限必填"
  
  belongs_to :user

  has_many :post_categories, dependent: :destroy
  has_many :categories, through: :post_categories

  has_many :replies, dependent: :destroy

  has_many :favorites, dependent: :destroy
  has_many :favorited_users, through: :favorites, source: :user

  def is_favorited?(user)
    self.favorited_users.include?(user)
  end

  def is_published?
    self.status == true
  end

  def self.check_authority(user)
    self.where("authority = ? OR user_id = ?", "All", user.id).or(where('authority = ? AND user_id IN (?)', "Friends", user.all_friends))
  end
    
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < ApplicationController
  
  before_action :authenticate_admin
  
  def index
    
  end
end

app/controllers/api/v1/posts_controller.rb
class Api::V1::PostsController < ApiController
  before_action :authenticate_user!, except: [:index]
  before_action :set_post, only: [:show, :update, :destroy]
  before_action :check_draft, only: [:show]
  before_action :check_authority, only: [:show]
  before_action :post_owner, only: [:update]

  def index
    @posts = Post.where("status = ? AND authority = ?", true, "All")

    if user_signed_in?
      @posts = @posts.check_authority(current_user)
    end
    render json: @posts
  end

  def show
    if current_user != @post.user
      @post.increment!(:viewed_count)
    end
    render json: {
      title: @post.title,
      categories: @post.categories.map(&:name),
      description: @post.description,
      image: @post.image,
      user_id: @post.user_id
    }
  end

  def create
    @post = current_user.posts.new(post_params)
    if params[:commit] == 'Save Draft'
      @post.status = false
      if @post.save
        render json: {
          message: "草稿儲存成功",
          result: @post
        }
      else
        render json: {
          errors: @post.errors
        }
      end
    else
      @post.status = true
      if @post.save
        render json: {
          message: "文章發佈成功",
          result: @post
        }
      else
        render json: {
          errors: @post.errors
        }
      end
    end
  end

  def update
    if current_user.admin? || current_user == @post.user
      if @post.status == true && params[:commit] == 'Update'
        if @post.update(post_params)
          render json: {
            message: "文章更新成功",
            result: @post
          }
        else
          render json: {
            errors: "文章更新失敗"
          }
        end
      elsif @post.status == false && params[:commit] == 'Submit'
        @post.status = true
        @post.viewed_count = 0

        if @post.update(post_params)
          render json: {
            message: "文章發佈成功",
            result: @post
          }
        else
          render json: {
            errors: "文章發布失敗"
          }
        end
      else
        if @post.update(post_params)
          render json: {
            message: "草稿更新成功",
            result: @post
          }
        else
          render json: {
            errors:"草稿更新失敗"
          }
        end
      end 
    end
  end

  def destroy
    @post.destroy
    if @post.status == true
      render json: {
        message: "文章內容已刪除"
      }
    else
      render json: {
        message: "草稿內容已刪除"
      }
    end
  end

  private

  def set_post
    if Post.find_by_id params[:id]
      @post = Post.find(params[:id])
    else
      render json: {
        message: "文章內容不存在",
        status: 400
      }
    end
  end

  def post_params
    params.permit(
      :title, 
      :description, 
      :image, 
      :authority,
      :category_ids => [])
  end

  def check_draft
    unless @post.is_published? || @post.user.id == current_user.id
      render json: {
        errors: "文章不公開"
      }
    end
  end

  def check_authority
    if @post.authority == "Myself"
      unless @post.user.id == current_user.id
        render json: {
        errors: "無此權限觀看文章"
      }
      end 
    elsif @post.authority == "Friends"
      unless @post.user.id == current_user.id || @post.user.all_friends.include?(current_user)
        render json: {
        errors: "無此權限觀看文章"
      }
      end 
    end   
  end

  def post_owner
    unless @post.user_id == current_user.id
      render json: {
        errors: "非文章擁有者無法編輯"
      }
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index]

  before_action :set_post, only: [:show, :edit, :update, :destroy, :favorite, :unfavorite, :post_owner, :check_draft, :check_authority]
  before_action :post_owner, only: [:edit, :update]
  before_action :check_draft, only: [:show]
  before_action :check_authority, only: [:show]

  layout "site_index", only: [:index, :sort]

  def index
    @categories = Category.all
    if user_signed_in?
      @posts = Post.where('status = ?', true).check_authority(current_user).order(created_at: :asc).page(params[:page]).per(20)
    else
      @posts = Post.where('status = ? AND authority = ?', true, "All").order(created_at: :asc).page(params[:page]).per(20)
    end
  end

  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.new(post_params)
    if params[:commit] == 'Save Draft'
      @post.status = false
      if @post.save
        flash[:notice] = "草稿儲存成功"
        redirect_to post_path(@post)
      else
        flash.now[:alert] = "草稿儲存失敗"
        render :new
      end
    else
      @post.status = true
      if @post.save
        flash[:notice] = "文章發布成功"
        redirect_to post_path(@post)
      else
        flash.now[:alert] = "文章發布失敗"
        render :new
      end
    end
  end

  def show
    @reply = Reply.new
    @replies = @post.replies.page(params[:page]).per(20)
    if current_user != @post.user
      @post.increment!(:viewed_count)
    end
  end

  def edit
    
  end

  def update
    if current_user.admin? || current_user == @post.user
      if @post.status == true && params[:commit] == 'Update'
        if @post.update(post_params)
          flash[:notice] = "文章更新成功"
          redirect_to post_path(@post)
        else
          flash.now[:alert] = "文章更新失敗"
          render :edit
        end
      elsif @post.status == false && params[:commit] == 'Submit'
        @post.status = true
        @post.viewed_count = 0

        if @post.update(post_params)
          flash[:notice] = "文章發布成功"
          redirect_to post_path(@post)
        else
          flash.now[:alert] = "文章發布失敗"
          render :edit
        end
      else
        if @post.update(post_params)
          flash[:notice] = "草稿更新成功"
          redirect_to post_path(@post)
        else
          flash.now[:alert] = "草稿更新失敗"
          render :edit
        end
      end 
    end
  end

  def destroy
    @post.destroy

    if @post.status == true
      redirect_to posts_path
      flash[:alert] = "文章內容已刪除"
    else
      redirect_to draft_user_path(@post.user)
      flash[:alert] = "草稿內容已刪除"
    end
    
  end

  def feeds
    @users = User.all
    @posts = Post.where('status = ?', true)
    @replies = Reply.all
    @popular_posts = @posts.sort_by { |s| s.replies.count } .reverse.take(10)
    @active_users = @users.sort_by { |s| s.replies.count } .reverse.take(10)
  end

  def sort
    @categories = Category.all

    if params[:category_id]
      @category = Category.find(params[:category_id])
      @posts = @category.posts.where('status = ?', true).check_authority(current_user)
    else
      @posts = Post.where('status = ?', true).check_authority(current_user)
    end

    if params[:replies_count]
      @posts = @posts.order(replies_count: :desc).page(params[:page]).per(20)
    elsif params[:last_replied_at]
      @posts = @posts.order(last_reply_created_at: :desc).page(params[:page]).per(20)    
    else
      @posts = @posts.order(viewed_count: :desc).page(params[:page]).per(20)
    end

  end

   def favorite
    @post.favorites.create!(user: current_user)
  end

  def unfavorite
    favorites = Favorite.where(post: @post, user: current_user)
    favorites.destroy_all
  end

  private

  def post_params
    params.require(:post).permit(
      :title, 
      :description, 
      :image, 
      :authority,
      :category_ids => [])
  end

  def set_post
    if Post.find_by_id params[:id]
      @post = Post.find(params[:id])
    else
      redirect_to posts_path
      flash[:alert] = "文章內容不存在"
    end
  end

  def post_owner
    unless @post.user_id == current_user.id
      flash[:alert] = '非文章擁有者無法編輯'
      redirect_to posts_path
    end
  end

  def check_draft
    unless @post.is_published? || @post.user.id == current_user.id
      flash[:alert] = '文章不公開'
      redirect_to posts_path
    end
  end

  def check_authority
    if @post.authority == "Myself"
      unless @post.user.id == current_user.id
        flash[:alert] = '無此權限觀看文章'
        redirect_to posts_path
      end 
    elsif @post.authority == "Friends"
      unless @post.user.id == current_user.id || @post.user.all_friends.include?(current_user)
        flash[:alert] = '無此權限觀看文章'
        redirect_to posts_path
      end 
    end   
  end
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/helpers/api/v1/posts_helper.rb
module Api::V1::PostsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/edit.html.erb
<div class="container">
  <%= render :partial => "shared/form" %>
</div>

app/views/posts/feeds.html.erb
<div class="feed-info row">
  <div class="col-md-4" >
    <p>User</p>
    <span><%= @users.count %></span>
  </div>
  <div class="col-md-4">
    <p>Post</p>
    <span><%= @posts.count %></span>
  </div>
  <div class="col-md-4">
    <p>Reply</p>
    <span><%= @replies.count %></span>
  </div>
</div>
<div class="container">
  <div class="row">
    <div class="col-md-12">
      
    </div>
    <div class="col-md-12" style="margin-top: 40px;">
      <div class="col-md-6">
        <h3 style="text-align: center;">Chatterbox</h3>
        <hr>
        <% @active_users.each do |user| %>
       <div class="media chatter-box">
          <div class="media-left col-md-2">
            <%= image_tag user.avatar , class:' img-circle', style: 'width:65px; height:65px;' if user.avatar?%>
              <%= image_tag "http://via.placeholder.com/60x60" , class:' img-circle'  unless user.avatar?%>
          </div>
          <div class="media-heading col-md-10">
            <h4>
              <%= link_to user.name, user_path(user)if user.name? %>
              <%= link_to user.email.split("@").first.upcase_first , user_path(user) unless user.name? %>
            </h4>
            <p><%= truncate(user.introduction, length:50) %></p>
          </div>
        </div>
        <% end %>
      </div>

      <div class="col-md-6">
        <h3 style="text-align: center;">Most Popular Post</h3>
        <hr>
        <% @popular_posts.each do |post| %>
        <div class="media chatter-box">
          <div class="media-left col-md-2">
            <%= image_tag post.image , class:' img-circle', style: 'width:65px; height:65px;' if post.image?%>
              <%= image_tag "http://via.placeholder.com/60x60" , class:' img-circle'  unless post.image?%>
          </div>
          <div class="media-heading col-md-10">
            <h4><%= link_to post.title, post_path(post) %></h4>
            <p><%= truncate(post.description, length:50) %></p>
          </div>
        </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/posts/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <ul class="main-tab">
        <li  role="presentation" class="active"><%= link_to "全部文章", root_path %></li>
        <% @categories.each do |category| %>
          <li role="presentation"><%= link_to category.name, category_path(category) %></li>
        <% end %>
      </ul>
      <br>
      <%= render partial: "shared/post_list" %>

    </div>

  </div>
</div>

app/views/posts/new.html.erb
<div class="container">
  <%= form_for  @post do |f| %>
    <%= f.label :title, "Title" %>
    <%= f.text_field :title, class:"form-control" %> <br>

    <%= f.label :description, "Description" %>
    <%= f.text_area :description, class:"form-control" %> <br>

    <%= f.label :image, "Photo" %>
    <%= image_tag @post.image, width: '300px' if @post.image? %>
    <%= f.file_field :image %> <br>

    <%= f.submit %>
  <% end %>
</div>

app/views/posts/show.html.erb
<div class="container">
  <div class="col-md-12 post-content" id="<%= @post.id %>">
    <h1>
      <%= @post.title %>
      <span class="post-info">
        Category： <%= @post.categories.map(&:name).join(' | ') %>
      </span>

      <% if @post.is_published? %>
      <div class="pull-right collect-post">
        <% if @post.is_favorited?(current_user) %>
          <span class="unfavorite-btn glyphicon glyphicon-heart text-danger"></span>
        <% else %>
          <span class="favorite-btn glyphicon glyphicon-heart"></span>
        <% end %>
      </div>
      <% else %>
        <small><span class="label label-danger pull-right">Draft</span></small>
      <% end %>
    </h1>
    <hr>

    <div class="col-md-2"  style="text-align: center;">
      <div>
      <%= image_tag @post.user.avatar, width: '150px' if @post.user.avatar?%>
      <%= image_tag "http://via.placeholder.com/150x150"  unless @post.user.avatar?%>
      </div>
      <h4>
        <%= link_to @post.user.name, user_path(@post.user) if @post.user.name? %>
        <%= link_to @post.user.email.split("@").first.upcase_first, user_path(@post.user) unless @post.user.name? %>
      </h4>
      <%= render partial: "shared/friend", locals: {user: @post.user} %>
    </div>

    <div class="col-md-10">
      <div>
        <%= image_tag @post.image, width: '600px', style: 'margin:15px' if @post.image?%>
        <%= image_tag "http://via.placeholder.com/600x400"  unless @post.image?%>
      </div>
      <p><%= @post.description %></p>
      
        <div class="pull-right">
          <% if @post.user == current_user %>
        <%= link_to '<i class="glyphicon glyphicon-pencil" aria-hidden="true"></i>'.html_safe, edit_post_path, class: 'btn btn-primary' %>
        <% end %>
        <% if current_user.admin? || @post.user == current_user %>
        <%= link_to '<i class="glyphicon glyphicon-trash" aria-hidden="true"></i>'.html_safe, post_path(@post), class: 'btn btn-danger', method: :delete, data: {confirm:"確定刪除這篇文章?"} %>
        <% end %>
        </div>
    </div>
  </div>

  <div class="col-md-12" id="replylist">
    <% if @post.status %>
      <% @replies.each do |reply| %>
        <div class="media"  id="<%= reply.id %>">

          <div class="media-left"  style="text-align: center">
          <%= image_tag reply.user.avatar, width: '100px' if reply.user.avatar?%>
            <%= image_tag "http://via.placeholder.com/100x100"  unless reply.user.avatar?%>
          <h5>
            <%= link_to reply.user.name, user_path(reply.user) if reply.user.name? %>
            <%= link_to reply.user.email.split("@").first.upcase_first, user_path(reply.user) unless reply.user.name? %> 
          </h5>
          <%= render partial: "shared/friend", locals: {user: reply.user} %>
          </div>

          <div class="media-body" style="padding-left: 30px;">
            <p class="reply-content"><%= reply.content %></p>
            <% if reply.user == current_user %>
              <div class="pull-right">
                <span class="edit-reply btn btn-default btn-sm glyphicon glyphicon-pencil"></span>
                <%= link_to reply_path(reply), method: :delete, data: {confirm:"確定刪除此留言?"} do %>
                  <span class="btn btn-default btn-sm glyphicon glyphicon-trash"></span>
                <% end %>
              </div>
            <% end %>
          </div>
          <hr>
        </div>
      <% end %>
      <div class="text-center">
        <%= paginate  @replies  %>
      </div>

      <%= form_for  @reply do |f| %>
        <div class="form-group">
          <%= f.text_area :content, placeholder: "add comment", class: "form-control", style: 'height: 150px; border-radius: 20px;' %>
        </div>
        <div class="form-group">
          <%= hidden_field_tag :post_id, @post.id %>
          <%= f.submit  'Submit', :class => 'btn btn-primary' %>
        </div>
      <% end %>
      
    <% end %>
  </div>
</div>

<script>
$(".collect-post").on('click', '.favorite-btn', function(event){
  var post_id = event.target.parentNode.parentNode.parentNode.id;
  console.log(post_id);

    $.ajax({
      url: "/posts/" + post_id + "/favorite" ,
      method: "POST",
      dataType: "json",
      success: function() {
        $(".post-content").find(".favorite-btn").remove();
        $(".post-content").find(".collect-post").append("<span class=\"unfavorite-btn glyphicon glyphicon-heart text-danger\"></span>");
        console.log(post_id);
      }
    });
});

$(".collect-post").on('click', '.unfavorite-btn', function(event){
  var post_id = event.target.parentNode.parentNode.parentNode.id;
  console.log(post_id);

    $.ajax({
      url: "/posts/" + post_id + "/unfavorite" ,
      method: "POST",
      dataType: "json",
      success: function() {
        $(".post-content").find(".unfavorite-btn").remove();
        $(".post-content").find(".collect-post").append("<span class=\"favorite-btn glyphicon glyphicon-heart\"></span>");
        console.log(post_id);
      }
    });
});
</script>

<script>
$("#replylist").on("click", ".edit-reply", function(event) {

  var id = event.target.parentNode.parentNode.parentNode.id;

  console.log(id);

  var content = $("#" + id).find(".reply-content");
  var textColumn = $("#" + id).find(".media-body");
  textColumn.html($("#edit-template").html());
  textColumn.find(".update-content").val(content.html());
      
  // Update Action
  textColumn.one("click", ".update-button", function(updateEvent){
    updateEvent.preventDefault();
    var id = updateEvent.target.parentNode.parentNode.id;


    $.ajax({
      url: "/replies/" + id ,
      method: "PATCH",
      dataType: "json",
      data: {
        reply: {
          content: textColumn.find(".update-content").val()
        }
      },
      success: function(updateData) {
        var textColumn = $("#" + id).find(".media-body");
        var content = textColumn.find(".update-content").val();
        console.log(content);
        console.log(id);

        textColumn.html('<p class="reply-content"></p> <div class=\"pull-right\"></div>');
        textColumn.find(".reply-content").html(content);

        textColumn.find('div').append("<span class=\"edit-reply btn btn-default btn-sm glyphicon glyphicon-pencil\"></span>");
        textColumn.find('div').append("<a data-confirm=\"確定刪除此留言?\" rel=\"nofollow\" data-method=\"delete\" href=\"/replies/"+ id +"\"><span class=\"btn btn-default btn-sm glyphicon glyphicon-trash\"></span></a>");

      }
    });
  });
});
</script>

<script type="text/template" id="edit-template">
  <input type="text_area" class="update-content form-control" style="height:80px;" />
  <br>
  <button class="update-button pull-right btn btn-primary" type="submit">Update</button>
</script>

app/views/posts/sort.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <ul class="main-tab">
        <% if params[:category_id] != nil %>
          <li  role="presentation"><%= link_to "全部文章", root_path %></li>
          <% @categories.each do |category| %>
            <li role="presentation" class="<%= "active" if category == @category %>">
              <%= link_to category.name, category_path(category) %>
            </li>
          <% end %>
        <% else %>
          <li  role="presentation" class="active"><%= link_to "全部文章", root_path %></li>
          <% @categories.each do |category| %>
            <li role="presentation"><%= link_to category.name, category_path(category) %></li>
          <% end %>
        <% end %>
      </ul>
      <br>
      <%= render partial: "shared/post_list" %>

    </div>

  </div>
</div>